namespace MoleculeClassifications;

public enum HTSCategory
{
    I_HYDROCARBONS,
    II_ALCHOHOLS,
    III_PHENOLS,
    IV_ETHERS,
    V_ALDEHYDES,
    VI_KETONES,
    VII_CARBOX_ACIDS,
    VIII_INNORGANIC_ESTERS,
    IX_NITROGENATED,
    X_ORGANOINORGANICS_HETEROCYCLES,
    XI_VITAMINS_HORMONES,
    XII_GLYCOSIDES_ALKALOIDS,
    XIII_OTHER_ORGANICS,
}

